### ISSUE TITLE
Large package issue

### ISSUE THREAD

**Issue by richardgavel** [Inedo/Inedo.UPack#13]
I created a upack with the Universal Package Explorer with one file in it (a 1.7 GB 7-zip file). However, it seems to cut something off, because the upack is only 1.3 GB and when unpacking it, the 7-zip file is only 1.3 GB.

**Comment by BenLubar** [comment]
It seems to truncate files at 2 GiB, but I don't think that can be fixed without using a different zip file API.

I'm not aware of anything that would cause it to truncate to any size other than that.

**Comment by skovsende** [comment]
I have reported the same problem in a upack.exe here: https://github.com/Inedo/upack/issues/46

I believe there is a way to use the ZipArchive class differently, but I will have to investigate a little more.

**Comment by skovsende** [comment]
To me it looks like the main problem is that UniversalFeedClient.GetPackageStreamAsync returns a ConnectStream, which isn't seekable - this make ZipArchive copy the entire stream into a MemoryStream, and that is, where I atleast, get a OutOfMemory exception.

I have a simple proof of concept hack where I save the data from the ConnectStream into a FileStream, and then give the FileStream to the UniversalPackage constructor. Since the FileStream is seekable the MemoryStream isn't created and memory usage is kept low.

The prrof of concept can be found here: https://github.com/skovsende/upack/commit/d325c4fc418a3f0e62c47f75a63d358f16155dcb

It would be nicer to do it in a more general way though - maybe add the possibility to the UniversalFeedClient to use a backing temp file, but I'd love to have @gdivis input on this.

**Comment by skovsende** [comment]
A simple way to fix it could be to inherit from DefaultApiResponse and override GetResponseStream to use a FileStream as backing...

**Comment by gdivis** [comment]
I'm not opposed to adding a flag for buffering responses.

The UniversalPackage class does appear to need to seek through the input stream because of the way it enumerates entries, so maybe another good fix is to have that class create a temporary FileStream if the source stream doesn't support seeking.

We'll do a pull request with both of those, if that sounds good to you.

**Comment by skovsende** [comment]
Sounds like a perfectly reasonable solution. 

Now I just need a upack release with that code included :)

**Comment by gdivis** [comment]
We'll release one today. Thanks for taking the time to review the code!
