### ISSUE TITLE
Allow custom PackageRegistry locations

### ISSUE THREAD

**Issue by wldevries** [Inedo/Inedo.UPack#9]
We are interested in using Upack to install large packages on disconnected machines from a USB disk. Would you be interested in allowing custom locations for `PackageRegistry`? This would allow us to use a common API for mirroring a feed to a local registry on a USB disk and use that to update machines in the field.

**Comment by apapadimoulis** [comment]
Wow, that's an interesting use case. Actually, we had it something like this spec'd out as [part of the Universal Package Registry](https://inedo.com/support/documentation/upack/universal-package-registry/types-locations), but I don't think it's implemented in any of the clients due to lack of usecases. 

Actually... I'd love to learn more... would you mind reaching out to me directly?   apapadimoulis - at -Inedo -dot - com . I'm quite keen on documenting & showcasing unique usecases like this; with your help, I think we could really share this idea with the community!

Oh and I'm curious, have you investigated [Romp](https://inedo.com/romp) yet? It's universal packages, but with installation built-in.

**Comment by gdivis** [comment]
Sounds good to me. I believe it would be absolutely trivial to add this to this library. Of course, having support in the other tooling will need command line arguments/config settings for this.

**Comment by gdivis** [comment]
We've made the constructor for the `PackageRegistry` class public and pushed a new package containing this fix to NuGet as 1.0.1. Hope this helps!
